// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository (interfaces: IApplicationRepository)
//
// Generated by this command:
//
//	mockgen -package=repomocks -destination=./internal/repository/mocks/application.mock.go github.com/Duke1616/eiam/internal/repository IApplicationRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIApplicationRepository is a mock of IApplicationRepository interface.
type MockIApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIApplicationRepositoryMockRecorder
	isgomock struct{}
}

// MockIApplicationRepositoryMockRecorder is the mock recorder for MockIApplicationRepository.
type MockIApplicationRepositoryMockRecorder struct {
	mock *MockIApplicationRepository
}

// NewMockIApplicationRepository creates a new mock instance.
func NewMockIApplicationRepository(ctrl *gomock.Controller) *MockIApplicationRepository {
	mock := &MockIApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockIApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIApplicationRepository) EXPECT() *MockIApplicationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIApplicationRepository) Create(ctx context.Context, app domain.Application) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIApplicationRepositoryMockRecorder) Create(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIApplicationRepository)(nil).Create), ctx, app)
}

// Delete mocks base method.
func (m *MockIApplicationRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIApplicationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIApplicationRepository)(nil).Delete), ctx, id)
}

// FindByClientID mocks base method.
func (m *MockIApplicationRepository) FindByClientID(ctx context.Context, clientID string) (domain.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByClientID", ctx, clientID)
	ret0, _ := ret[0].(domain.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByClientID indicates an expected call of FindByClientID.
func (mr *MockIApplicationRepositoryMockRecorder) FindByClientID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByClientID", reflect.TypeOf((*MockIApplicationRepository)(nil).FindByClientID), ctx, clientID)
}

// FindByID mocks base method.
func (m *MockIApplicationRepository) FindByID(ctx context.Context, id int64) (domain.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIApplicationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIApplicationRepository)(nil).FindByID), ctx, id)
}

// ListByTenantID mocks base method.
func (m *MockIApplicationRepository) ListByTenantID(ctx context.Context, tenantID int64, offset, limit int) ([]domain.Application, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenantID", ctx, tenantID, offset, limit)
	ret0, _ := ret[0].([]domain.Application)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByTenantID indicates an expected call of ListByTenantID.
func (mr *MockIApplicationRepositoryMockRecorder) ListByTenantID(ctx, tenantID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantID", reflect.TypeOf((*MockIApplicationRepository)(nil).ListByTenantID), ctx, tenantID, offset, limit)
}

// Update mocks base method.
func (m *MockIApplicationRepository) Update(ctx context.Context, app domain.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIApplicationRepositoryMockRecorder) Update(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIApplicationRepository)(nil).Update), ctx, app)
}

// UpdateSecret mocks base method.
func (m *MockIApplicationRepository) UpdateSecret(ctx context.Context, id int64, secretHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, id, secretHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockIApplicationRepositoryMockRecorder) UpdateSecret(ctx, id, secretHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockIApplicationRepository)(nil).UpdateSecret), ctx, id, secretHash)
}
