// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository (interfaces: IOAuthClientRepository)
//
// Generated by this command:
//
//	mockgen -package=repomocks -destination=./mocks/oauth_client.mock.go github.com/Duke1616/eiam/internal/repository IOAuthClientRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIOAuthClientRepository is a mock of IOAuthClientRepository interface.
type MockIOAuthClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOAuthClientRepositoryMockRecorder
	isgomock struct{}
}

// MockIOAuthClientRepositoryMockRecorder is the mock recorder for MockIOAuthClientRepository.
type MockIOAuthClientRepositoryMockRecorder struct {
	mock *MockIOAuthClientRepository
}

// NewMockIOAuthClientRepository creates a new mock instance.
func NewMockIOAuthClientRepository(ctrl *gomock.Controller) *MockIOAuthClientRepository {
	mock := &MockIOAuthClientRepository{ctrl: ctrl}
	mock.recorder = &MockIOAuthClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOAuthClientRepository) EXPECT() *MockIOAuthClientRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIOAuthClientRepository) Create(ctx context.Context, client domain.OAuthClient) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, client)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIOAuthClientRepositoryMockRecorder) Create(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIOAuthClientRepository)(nil).Create), ctx, client)
}

// Delete mocks base method.
func (m *MockIOAuthClientRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIOAuthClientRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIOAuthClientRepository)(nil).Delete), ctx, id)
}

// FindByClientID mocks base method.
func (m *MockIOAuthClientRepository) FindByClientID(ctx context.Context, clientID string) (domain.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByClientID", ctx, clientID)
	ret0, _ := ret[0].(domain.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByClientID indicates an expected call of FindByClientID.
func (mr *MockIOAuthClientRepositoryMockRecorder) FindByClientID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByClientID", reflect.TypeOf((*MockIOAuthClientRepository)(nil).FindByClientID), ctx, clientID)
}

// FindByID mocks base method.
func (m *MockIOAuthClientRepository) FindByID(ctx context.Context, id int64) (domain.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIOAuthClientRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIOAuthClientRepository)(nil).FindByID), ctx, id)
}

// ListByTenantID mocks base method.
func (m *MockIOAuthClientRepository) ListByTenantID(ctx context.Context, tenantID int64, offset, limit int) ([]domain.OAuthClient, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenantID", ctx, tenantID, offset, limit)
	ret0, _ := ret[0].([]domain.OAuthClient)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByTenantID indicates an expected call of ListByTenantID.
func (mr *MockIOAuthClientRepositoryMockRecorder) ListByTenantID(ctx, tenantID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantID", reflect.TypeOf((*MockIOAuthClientRepository)(nil).ListByTenantID), ctx, tenantID, offset, limit)
}

// Update mocks base method.
func (m *MockIOAuthClientRepository) Update(ctx context.Context, client domain.OAuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIOAuthClientRepositoryMockRecorder) Update(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIOAuthClientRepository)(nil).Update), ctx, client)
}

// UpdateSecret mocks base method.
func (m *MockIOAuthClientRepository) UpdateSecret(ctx context.Context, id int64, secretHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, id, secretHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockIOAuthClientRepositoryMockRecorder) UpdateSecret(ctx, id, secretHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockIOAuthClientRepository)(nil).UpdateSecret), ctx, id, secretHash)
}
