// Code generated by MockGen. DO NOT EDIT.
// Source: ./permission.go
//
// Generated by this command:
//
//	mockgen -source=./permission.go -package=permissionmocks -destination=./mocks/permission.mock.go -typed IPermissionService
//

// Package permissionmocks is a generated GoMock package.
package permissionmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIPermissionService is a mock of IPermissionService interface.
type MockIPermissionService struct {
	ctrl     *gomock.Controller
	recorder *MockIPermissionServiceMockRecorder
	isgomock struct{}
}

// MockIPermissionServiceMockRecorder is the mock recorder for MockIPermissionService.
type MockIPermissionServiceMockRecorder struct {
	mock *MockIPermissionService
}

// NewMockIPermissionService creates a new mock instance.
func NewMockIPermissionService(ctrl *gomock.Controller) *MockIPermissionService {
	mock := &MockIPermissionService{ctrl: ctrl}
	mock.recorder = &MockIPermissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPermissionService) EXPECT() *MockIPermissionServiceMockRecorder {
	return m.recorder
}

// AssignRoleToUser mocks base method.
func (m *MockIPermissionService) AssignRoleToUser(ctx context.Context, tenantId, userId int64, roleCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToUser", ctx, tenantId, userId, roleCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignRoleToUser indicates an expected call of AssignRoleToUser.
func (mr *MockIPermissionServiceMockRecorder) AssignRoleToUser(ctx, tenantId, userId, roleCode any) *MockIPermissionServiceAssignRoleToUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToUser", reflect.TypeOf((*MockIPermissionService)(nil).AssignRoleToUser), ctx, tenantId, userId, roleCode)
	return &MockIPermissionServiceAssignRoleToUserCall{Call: call}
}

// MockIPermissionServiceAssignRoleToUserCall wrap *gomock.Call
type MockIPermissionServiceAssignRoleToUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceAssignRoleToUserCall) Return(arg0 bool, arg1 error) *MockIPermissionServiceAssignRoleToUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceAssignRoleToUserCall) Do(f func(context.Context, int64, int64, string) (bool, error)) *MockIPermissionServiceAssignRoleToUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceAssignRoleToUserCall) DoAndReturn(f func(context.Context, int64, int64, string) (bool, error)) *MockIPermissionServiceAssignRoleToUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BindResourceToPermission mocks base method.
func (m *MockIPermissionService) BindResourceToPermission(ctx context.Context, tenantId int64, permCode string, resType domain.ResourceType, resIds []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindResourceToPermission", ctx, tenantId, permCode, resType, resIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindResourceToPermission indicates an expected call of BindResourceToPermission.
func (mr *MockIPermissionServiceMockRecorder) BindResourceToPermission(ctx, tenantId, permCode, resType, resIds any) *MockIPermissionServiceBindResourceToPermissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindResourceToPermission", reflect.TypeOf((*MockIPermissionService)(nil).BindResourceToPermission), ctx, tenantId, permCode, resType, resIds)
	return &MockIPermissionServiceBindResourceToPermissionCall{Call: call}
}

// MockIPermissionServiceBindResourceToPermissionCall wrap *gomock.Call
type MockIPermissionServiceBindResourceToPermissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceBindResourceToPermissionCall) Return(arg0 error) *MockIPermissionServiceBindResourceToPermissionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceBindResourceToPermissionCall) Do(f func(context.Context, int64, string, domain.ResourceType, []int64) error) *MockIPermissionServiceBindResourceToPermissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceBindResourceToPermissionCall) DoAndReturn(f func(context.Context, int64, string, domain.ResourceType, []int64) error) *MockIPermissionServiceBindResourceToPermissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckAPI mocks base method.
func (m *MockIPermissionService) CheckAPI(ctx context.Context, tenantId, userId int64, serviceName, method, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAPI", ctx, tenantId, userId, serviceName, method, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAPI indicates an expected call of CheckAPI.
func (mr *MockIPermissionServiceMockRecorder) CheckAPI(ctx, tenantId, userId, serviceName, method, path any) *MockIPermissionServiceCheckAPICall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAPI", reflect.TypeOf((*MockIPermissionService)(nil).CheckAPI), ctx, tenantId, userId, serviceName, method, path)
	return &MockIPermissionServiceCheckAPICall{Call: call}
}

// MockIPermissionServiceCheckAPICall wrap *gomock.Call
type MockIPermissionServiceCheckAPICall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceCheckAPICall) Return(arg0 bool, arg1 error) *MockIPermissionServiceCheckAPICall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceCheckAPICall) Do(f func(context.Context, int64, int64, string, string, string) (bool, error)) *MockIPermissionServiceCheckAPICall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceCheckAPICall) DoAndReturn(f func(context.Context, int64, int64, string, string, string) (bool, error)) *MockIPermissionServiceCheckAPICall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckPermission mocks base method.
func (m *MockIPermissionService) CheckPermission(ctx context.Context, tenantId, userId int64, action, resource string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, tenantId, userId, action, resource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockIPermissionServiceMockRecorder) CheckPermission(ctx, tenantId, userId, action, resource any) *MockIPermissionServiceCheckPermissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockIPermissionService)(nil).CheckPermission), ctx, tenantId, userId, action, resource)
	return &MockIPermissionServiceCheckPermissionCall{Call: call}
}

// MockIPermissionServiceCheckPermissionCall wrap *gomock.Call
type MockIPermissionServiceCheckPermissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceCheckPermissionCall) Return(arg0 bool, arg1 error) *MockIPermissionServiceCheckPermissionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceCheckPermissionCall) Do(f func(context.Context, int64, int64, string, string) (bool, error)) *MockIPermissionServiceCheckPermissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceCheckPermissionCall) DoAndReturn(f func(context.Context, int64, int64, string, string) (bool, error)) *MockIPermissionServiceCheckPermissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateAPI mocks base method.
func (m *MockIPermissionService) CreateAPI(ctx context.Context, a domain.API) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPI", ctx, a)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPI indicates an expected call of CreateAPI.
func (mr *MockIPermissionServiceMockRecorder) CreateAPI(ctx, a any) *MockIPermissionServiceCreateAPICall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPI", reflect.TypeOf((*MockIPermissionService)(nil).CreateAPI), ctx, a)
	return &MockIPermissionServiceCreateAPICall{Call: call}
}

// MockIPermissionServiceCreateAPICall wrap *gomock.Call
type MockIPermissionServiceCreateAPICall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceCreateAPICall) Return(arg0 int64, arg1 error) *MockIPermissionServiceCreateAPICall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceCreateAPICall) Do(f func(context.Context, domain.API) (int64, error)) *MockIPermissionServiceCreateAPICall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceCreateAPICall) DoAndReturn(f func(context.Context, domain.API) (int64, error)) *MockIPermissionServiceCreateAPICall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateMenu mocks base method.
func (m_2 *MockIPermissionService) CreateMenu(ctx context.Context, m domain.Menu) (int64, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateMenu", ctx, m)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMenu indicates an expected call of CreateMenu.
func (mr *MockIPermissionServiceMockRecorder) CreateMenu(ctx, m any) *MockIPermissionServiceCreateMenuCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenu", reflect.TypeOf((*MockIPermissionService)(nil).CreateMenu), ctx, m)
	return &MockIPermissionServiceCreateMenuCall{Call: call}
}

// MockIPermissionServiceCreateMenuCall wrap *gomock.Call
type MockIPermissionServiceCreateMenuCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceCreateMenuCall) Return(arg0 int64, arg1 error) *MockIPermissionServiceCreateMenuCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceCreateMenuCall) Do(f func(context.Context, domain.Menu) (int64, error)) *MockIPermissionServiceCreateMenuCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceCreateMenuCall) DoAndReturn(f func(context.Context, domain.Menu) (int64, error)) *MockIPermissionServiceCreateMenuCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatePermission mocks base method.
func (m *MockIPermissionService) CreatePermission(ctx context.Context, p domain.Permission) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", ctx, p)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockIPermissionServiceMockRecorder) CreatePermission(ctx, p any) *MockIPermissionServiceCreatePermissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockIPermissionService)(nil).CreatePermission), ctx, p)
	return &MockIPermissionServiceCreatePermissionCall{Call: call}
}

// MockIPermissionServiceCreatePermissionCall wrap *gomock.Call
type MockIPermissionServiceCreatePermissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceCreatePermissionCall) Return(arg0 int64, arg1 error) *MockIPermissionServiceCreatePermissionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceCreatePermissionCall) Do(f func(context.Context, domain.Permission) (int64, error)) *MockIPermissionServiceCreatePermissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceCreatePermissionCall) DoAndReturn(f func(context.Context, domain.Permission) (int64, error)) *MockIPermissionServiceCreatePermissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAuthorizedMenus mocks base method.
func (m *MockIPermissionService) GetAuthorizedMenus(ctx context.Context, tenantId, userId int64) ([]domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizedMenus", ctx, tenantId, userId)
	ret0, _ := ret[0].([]domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizedMenus indicates an expected call of GetAuthorizedMenus.
func (mr *MockIPermissionServiceMockRecorder) GetAuthorizedMenus(ctx, tenantId, userId any) *MockIPermissionServiceGetAuthorizedMenusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizedMenus", reflect.TypeOf((*MockIPermissionService)(nil).GetAuthorizedMenus), ctx, tenantId, userId)
	return &MockIPermissionServiceGetAuthorizedMenusCall{Call: call}
}

// MockIPermissionServiceGetAuthorizedMenusCall wrap *gomock.Call
type MockIPermissionServiceGetAuthorizedMenusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceGetAuthorizedMenusCall) Return(arg0 []domain.Menu, arg1 error) *MockIPermissionServiceGetAuthorizedMenusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceGetAuthorizedMenusCall) Do(f func(context.Context, int64, int64) ([]domain.Menu, error)) *MockIPermissionServiceGetAuthorizedMenusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceGetAuthorizedMenusCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Menu, error)) *MockIPermissionServiceGetAuthorizedMenusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRolesForUser mocks base method.
func (m *MockIPermissionService) GetRolesForUser(ctx context.Context, tenantId, userId int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesForUser", ctx, tenantId, userId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesForUser indicates an expected call of GetRolesForUser.
func (mr *MockIPermissionServiceMockRecorder) GetRolesForUser(ctx, tenantId, userId any) *MockIPermissionServiceGetRolesForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesForUser", reflect.TypeOf((*MockIPermissionService)(nil).GetRolesForUser), ctx, tenantId, userId)
	return &MockIPermissionServiceGetRolesForUserCall{Call: call}
}

// MockIPermissionServiceGetRolesForUserCall wrap *gomock.Call
type MockIPermissionServiceGetRolesForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPermissionServiceGetRolesForUserCall) Return(arg0 []string, arg1 error) *MockIPermissionServiceGetRolesForUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPermissionServiceGetRolesForUserCall) Do(f func(context.Context, int64, int64) ([]string, error)) *MockIPermissionServiceGetRolesForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPermissionServiceGetRolesForUserCall) DoAndReturn(f func(context.Context, int64, int64) ([]string, error)) *MockIPermissionServiceGetRolesForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
