// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/eiam/internal/repository"
	"github.com/Duke1616/eiam/internal/repository/dao"
	"github.com/Duke1616/eiam/internal/service/permission"
	"github.com/Duke1616/eiam/internal/service/resource"
	"github.com/Duke1616/eiam/internal/service/role"
	"github.com/Duke1616/eiam/internal/service/tenant"
	"github.com/Duke1616/eiam/internal/service/user"
	permission2 "github.com/Duke1616/eiam/internal/web/permission"
	"github.com/Duke1616/eiam/internal/web/policy"
	resource2 "github.com/Duke1616/eiam/internal/web/resource"
	role2 "github.com/Duke1616/eiam/internal/web/role"
	tenant2 "github.com/Duke1616/eiam/internal/web/tenant"
	user2 "github.com/Duke1616/eiam/internal/web/user"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cmdable := InitRedis()
	provider := InitSession(cmdable)
	listener := InitListener()
	v := InitGinMiddlewares(provider)
	db := InitDB()
	iUserDAO := dao.NewUserDAO(db)
	iTenantDAO := dao.NewTenantDAO(db)
	iUserRepository := repository.NewUserRepository(iUserDAO, iTenantDAO)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	syncedEnforcer := InitCasbin(db)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iRoleService := role.NewRoleService(iRoleRepository)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository)
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO)
	iAuthorizer := InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iRoleService, iResourceService, iPermissionRepository, iAuthorizer)
	iTenantService := tenant.NewTenantService(iTenantRepository, iPermissionService, iRoleService)
	config := InitLdapConfig()
	v2 := InitIdentityProviders(config)
	iUserService := user.NewUserService(iUserRepository, iTenantService, v2, iPermissionService)
	handler := user2.NewUserHandler(iUserService, provider)
	policyHandler := policy.NewHandler(iPermissionService, provider)
	tenantHandler := tenant2.NewHandler(iTenantService, provider)
	permissionHandler := permission2.NewHandler(iPermissionService)
	roleHandler := role2.NewHandler(iRoleService, iPermissionService)
	string2 := InitServiceConfig()
	iInitializer := resource.NewResourceInitializer(iResourceRepository, iPermissionRepository, string2)
	resourceHandler := resource2.NewHandler(iInitializer)
	component := InitGinWebServer(provider, listener, v, handler, policyHandler, tenantHandler, permissionHandler, roleHandler, resourceHandler)
	v3 := InitProviders()
	app := &App{
		Web:         component,
		Init:        iInitializer,
		ResourceHdl: resourceHandler,
		Providers:   v3,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(
	InitDB,
	InitRedis,
	InitSession,
	InitCasbin,
	InitListener,
	InitOPA,

	InitLdapConfig,
	InitIdentityProviders,

	InitServiceConfig,
)
