// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/eiam/internal/repository"
	"github.com/Duke1616/eiam/internal/repository/dao"
	"github.com/Duke1616/eiam/internal/service/permission"
	"github.com/Duke1616/eiam/internal/service/resource"
	"github.com/Duke1616/eiam/internal/service/role"
	"github.com/Duke1616/eiam/internal/service/tenant"
	"github.com/Duke1616/eiam/internal/service/user"
	"github.com/Duke1616/eiam/internal/web/policy"
	tenant2 "github.com/Duke1616/eiam/internal/web/tenant"
	user2 "github.com/Duke1616/eiam/internal/web/user"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cmdable := InitRedis()
	provider := InitSession(cmdable)
	listener := InitListener()
	v := InitGinMiddlewares(provider)
	db := InitDB()
	iUserDAO := dao.NewUserDAO(db)
	iUserRepository := repository.NewUserRepository(iUserDAO)
	config := InitLdapConfig()
	v2 := InitIdentityProviders(config)
	iUserService := user.NewUserService(iUserRepository, v2)
	handler := user2.NewUserHandler(iUserService)
	syncedEnforcer := InitCasbin(db)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iRoleService := role.NewRoleService(iRoleRepository)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository)
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO)
	iAuthorizer := InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iRoleService, iResourceService, iPermissionRepository, iAuthorizer)
	policyHandler := policy.NewHandler(iPermissionService, provider)
	iTenantDAO := dao.NewTenantDAO(db)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	iTenantService := tenant.NewTenantService(iTenantRepository)
	tenantHandler := tenant2.NewHandler(iTenantService, provider)
	component := InitGinWebServer(provider, listener, v, handler, policyHandler, tenantHandler)
	app := &App{
		Web: component,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(
	InitDB,
	InitRedis,
	InitSession,
	InitCasbin,
	InitListener,
	InitOPA,

	InitLdapConfig,
	InitIdentityProviders,
)
