// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/eiam/internal/repository"
	"github.com/Duke1616/eiam/internal/repository/cache"
	"github.com/Duke1616/eiam/internal/repository/dao"
	"github.com/Duke1616/eiam/internal/service/permission"
	"github.com/Duke1616/eiam/internal/service/policy"
	"github.com/Duke1616/eiam/internal/service/resource"
	"github.com/Duke1616/eiam/internal/service/role"
	"github.com/Duke1616/eiam/internal/service/tenant"
	"github.com/Duke1616/eiam/internal/service/user"
	permission2 "github.com/Duke1616/eiam/internal/web/permission"
	policy2 "github.com/Duke1616/eiam/internal/web/policy"
	resource2 "github.com/Duke1616/eiam/internal/web/resource"
	role2 "github.com/Duke1616/eiam/internal/web/role"
	tenant2 "github.com/Duke1616/eiam/internal/web/tenant"
	user2 "github.com/Duke1616/eiam/internal/web/user"
	"github.com/RediSearch/redisearch-go/v2/redisearch"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cmdable := InitRedis()
	provider := InitSession(cmdable)
	listener := InitListener()
	v := InitGinMiddlewares(provider)
	db := InitDB()
	iUserDAO := dao.NewUserDAO(db)
	iTenantDAO := dao.NewTenantDAO(db)
	iUserRepository := repository.NewUserRepository(iUserDAO, iTenantDAO)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iPolicyDAO := dao.NewPolicyDAO(db)
	iPolicyRepository := repository.NewPolicyRepository(iPolicyDAO)
	iPolicyService := policy.NewPolicyService(iPolicyRepository)
	iRoleService := role.NewRoleService(iRoleRepository, iPolicyService)
	syncedEnforcer := InitCasbin(db)
	iTenantService := tenant.NewTenantService(iTenantRepository, iRoleService, syncedEnforcer)
	config := InitLdapConfig()
	v2 := InitIdentityProviders(config)
	iUserService := user.NewUserService(iUserRepository, iTenantService, v2)
	client := InitRedisSearch()
	redisearchLdapUserCache := InitLdapUserCache(client)
	ldapService := user.NewLdapService(iUserRepository, config, redisearchLdapUserCache)
	handler := user2.NewUserHandler(iUserService, iTenantService, ldapService, provider)
	policyHandler := policy2.NewHandler(iPolicyService, iUserService)
	iSubjectRegistry := InitSearchSubjectProviders(iRoleService, iUserService)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO)
	iServiceDAO := dao.NewServiceDAO(db)
	iServiceRepository := repository.NewServiceRepository(iServiceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository, iServiceRepository)
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO)
	iAuthorizer := InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iPolicyService, iRoleService, iSubjectRegistry, iResourceService, iPermissionRepository, iAuthorizer)
	tenantHandler := tenant2.NewHandler(iTenantService, iPermissionService, provider)
	permissionHandler := permission2.NewHandler(iPermissionService, provider)
	roleHandler := role2.NewHandler(iRoleService, iPermissionService, iUserService)
	string2 := InitServiceConfig()
	iInitializer := resource.NewResourceInitializer(iResourceRepository, iPermissionRepository, iResourceService, string2)
	resourceHandler := resource2.NewHandler(iInitializer)
	component := InitGinWebServer(provider, listener, v, handler, policyHandler, tenantHandler, permissionHandler, roleHandler, resourceHandler, iPermissionService)
	v3 := InitProviders()
	app := &App{
		Web:         component,
		Init:        iInitializer,
		ResourceHdl: resourceHandler,
		Providers:   v3,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(
	InitDB,
	InitRedis,
	InitSession,
	InitCasbin,
	InitListener,
	InitOPA,

	InitRedisSearch,
	InitLdapConfig,
	InitIdentityProviders,

	InitServiceConfig,
)

func InitLdapUserCache(conn *redisearch.Client) cache.RedisearchLdapUserCache {
	return cache.NewRedisearchLdapUserCache(conn)
}
