// Code generated by MockGen. DO NOT EDIT.
// Source: ./tenant.go
//
// Generated by this command:
//
//	mockgen -source=./tenant.go -package=tenantmocks -destination=./mocks/tenant.mock.go -typed ITenantService
//

// Package tenantmocks is a generated GoMock package.
package tenantmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockITenantService is a mock of ITenantService interface.
type MockITenantService struct {
	ctrl     *gomock.Controller
	recorder *MockITenantServiceMockRecorder
	isgomock struct{}
}

// MockITenantServiceMockRecorder is the mock recorder for MockITenantService.
type MockITenantServiceMockRecorder struct {
	mock *MockITenantService
}

// NewMockITenantService creates a new mock instance.
func NewMockITenantService(ctrl *gomock.Controller) *MockITenantService {
	mock := &MockITenantService{ctrl: ctrl}
	mock.recorder = &MockITenantServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITenantService) EXPECT() *MockITenantServiceMockRecorder {
	return m.recorder
}

// CreateTenant mocks base method.
func (m *MockITenantService) CreateTenant(ctx context.Context, name, code string, ownerId int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, name, code, ownerId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockITenantServiceMockRecorder) CreateTenant(ctx, name, code, ownerId any) *MockITenantServiceCreateTenantCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockITenantService)(nil).CreateTenant), ctx, name, code, ownerId)
	return &MockITenantServiceCreateTenantCall{Call: call}
}

// MockITenantServiceCreateTenantCall wrap *gomock.Call
type MockITenantServiceCreateTenantCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceCreateTenantCall) Return(arg0 int64, arg1 error) *MockITenantServiceCreateTenantCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceCreateTenantCall) Do(f func(context.Context, string, string, int64) (int64, error)) *MockITenantServiceCreateTenantCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceCreateTenantCall) DoAndReturn(f func(context.Context, string, string, int64) (int64, error)) *MockITenantServiceCreateTenantCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitPersonalTenant mocks base method.
func (m *MockITenantService) InitPersonalTenant(ctx context.Context, userId int64, username string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitPersonalTenant", ctx, userId, username)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitPersonalTenant indicates an expected call of InitPersonalTenant.
func (mr *MockITenantServiceMockRecorder) InitPersonalTenant(ctx, userId, username any) *MockITenantServiceInitPersonalTenantCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitPersonalTenant", reflect.TypeOf((*MockITenantService)(nil).InitPersonalTenant), ctx, userId, username)
	return &MockITenantServiceInitPersonalTenantCall{Call: call}
}

// MockITenantServiceInitPersonalTenantCall wrap *gomock.Call
type MockITenantServiceInitPersonalTenantCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceInitPersonalTenantCall) Return(arg0 int64, arg1 error) *MockITenantServiceInitPersonalTenantCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceInitPersonalTenantCall) Do(f func(context.Context, int64, string) (int64, error)) *MockITenantServiceInitPersonalTenantCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceInitPersonalTenantCall) DoAndReturn(f func(context.Context, int64, string) (int64, error)) *MockITenantServiceInitPersonalTenantCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListUserTenants mocks base method.
func (m *MockITenantService) ListUserTenants(ctx context.Context, userId int64) ([]domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserTenants", ctx, userId)
	ret0, _ := ret[0].([]domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserTenants indicates an expected call of ListUserTenants.
func (mr *MockITenantServiceMockRecorder) ListUserTenants(ctx, userId any) *MockITenantServiceListUserTenantsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserTenants", reflect.TypeOf((*MockITenantService)(nil).ListUserTenants), ctx, userId)
	return &MockITenantServiceListUserTenantsCall{Call: call}
}

// MockITenantServiceListUserTenantsCall wrap *gomock.Call
type MockITenantServiceListUserTenantsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceListUserTenantsCall) Return(arg0 []domain.Tenant, arg1 error) *MockITenantServiceListUserTenantsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceListUserTenantsCall) Do(f func(context.Context, int64) ([]domain.Tenant, error)) *MockITenantServiceListUserTenantsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceListUserTenantsCall) DoAndReturn(f func(context.Context, int64) ([]domain.Tenant, error)) *MockITenantServiceListUserTenantsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
