// Code generated by MockGen. DO NOT EDIT.
// Source: ./role.go
//
// Generated by this command:
//
//	mockgen -source=./role.go -package=rolemocks -destination=./mocks/role.mock.go -typed IRoleService
//

// Package rolemocks is a generated GoMock package.
package rolemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIRoleService is a mock of IRoleService interface.
type MockIRoleService struct {
	ctrl     *gomock.Controller
	recorder *MockIRoleServiceMockRecorder
	isgomock struct{}
}

// MockIRoleServiceMockRecorder is the mock recorder for MockIRoleService.
type MockIRoleServiceMockRecorder struct {
	mock *MockIRoleService
}

// NewMockIRoleService creates a new mock instance.
func NewMockIRoleService(ctrl *gomock.Controller) *MockIRoleService {
	mock := &MockIRoleService{ctrl: ctrl}
	mock.recorder = &MockIRoleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRoleService) EXPECT() *MockIRoleServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRoleService) Create(ctx context.Context, r domain.Role) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIRoleServiceMockRecorder) Create(ctx, r any) *MockIRoleServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRoleService)(nil).Create), ctx, r)
	return &MockIRoleServiceCreateCall{Call: call}
}

// MockIRoleServiceCreateCall wrap *gomock.Call
type MockIRoleServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceCreateCall) Return(arg0 int64, arg1 error) *MockIRoleServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceCreateCall) Do(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceCreateCall) DoAndReturn(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByCode mocks base method.
func (m *MockIRoleService) GetByCode(ctx context.Context, tenantId int64, code string) (domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, tenantId, code)
	ret0, _ := ret[0].(domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockIRoleServiceMockRecorder) GetByCode(ctx, tenantId, code any) *MockIRoleServiceGetByCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockIRoleService)(nil).GetByCode), ctx, tenantId, code)
	return &MockIRoleServiceGetByCodeCall{Call: call}
}

// MockIRoleServiceGetByCodeCall wrap *gomock.Call
type MockIRoleServiceGetByCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceGetByCodeCall) Return(arg0 domain.Role, arg1 error) *MockIRoleServiceGetByCodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceGetByCodeCall) Do(f func(context.Context, int64, string) (domain.Role, error)) *MockIRoleServiceGetByCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceGetByCodeCall) DoAndReturn(f func(context.Context, int64, string) (domain.Role, error)) *MockIRoleServiceGetByCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIRoleService) List(ctx context.Context, tenantId, offset, limit int64) ([]domain.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantId, offset, limit)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIRoleServiceMockRecorder) List(ctx, tenantId, offset, limit any) *MockIRoleServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIRoleService)(nil).List), ctx, tenantId, offset, limit)
	return &MockIRoleServiceListCall{Call: call}
}

// MockIRoleServiceListCall wrap *gomock.Call
type MockIRoleServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceListCall) Return(arg0 []domain.Role, arg1 int64, arg2 error) *MockIRoleServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceListCall) Do(f func(context.Context, int64, int64, int64) ([]domain.Role, int64, error)) *MockIRoleServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceListCall) DoAndReturn(f func(context.Context, int64, int64, int64) ([]domain.Role, int64, error)) *MockIRoleServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByIncludeCodes mocks base method.
func (m *MockIRoleService) ListByIncludeCodes(ctx context.Context, tenantId int64, codes []string) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIncludeCodes", ctx, tenantId, codes)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIncludeCodes indicates an expected call of ListByIncludeCodes.
func (mr *MockIRoleServiceMockRecorder) ListByIncludeCodes(ctx, tenantId, codes any) *MockIRoleServiceListByIncludeCodesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIncludeCodes", reflect.TypeOf((*MockIRoleService)(nil).ListByIncludeCodes), ctx, tenantId, codes)
	return &MockIRoleServiceListByIncludeCodesCall{Call: call}
}

// MockIRoleServiceListByIncludeCodesCall wrap *gomock.Call
type MockIRoleServiceListByIncludeCodesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceListByIncludeCodesCall) Return(arg0 []domain.Role, arg1 error) *MockIRoleServiceListByIncludeCodesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceListByIncludeCodesCall) Do(f func(context.Context, int64, []string) ([]domain.Role, error)) *MockIRoleServiceListByIncludeCodesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceListByIncludeCodesCall) DoAndReturn(f func(context.Context, int64, []string) ([]domain.Role, error)) *MockIRoleServiceListByIncludeCodesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockIRoleService) Update(ctx context.Context, r domain.Role) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIRoleServiceMockRecorder) Update(ctx, r any) *MockIRoleServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRoleService)(nil).Update), ctx, r)
	return &MockIRoleServiceUpdateCall{Call: call}
}

// MockIRoleServiceUpdateCall wrap *gomock.Call
type MockIRoleServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceUpdateCall) Return(arg0 int64, arg1 error) *MockIRoleServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceUpdateCall) Do(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdatePolicies mocks base method.
func (m *MockIRoleService) UpdatePolicies(ctx context.Context, tenantId int64, roleCode string, policies []domain.Policy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicies", ctx, tenantId, roleCode, policies)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePolicies indicates an expected call of UpdatePolicies.
func (mr *MockIRoleServiceMockRecorder) UpdatePolicies(ctx, tenantId, roleCode, policies any) *MockIRoleServiceUpdatePoliciesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicies", reflect.TypeOf((*MockIRoleService)(nil).UpdatePolicies), ctx, tenantId, roleCode, policies)
	return &MockIRoleServiceUpdatePoliciesCall{Call: call}
}

// MockIRoleServiceUpdatePoliciesCall wrap *gomock.Call
type MockIRoleServiceUpdatePoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceUpdatePoliciesCall) Return(arg0 error) *MockIRoleServiceUpdatePoliciesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceUpdatePoliciesCall) Do(f func(context.Context, int64, string, []domain.Policy) error) *MockIRoleServiceUpdatePoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceUpdatePoliciesCall) DoAndReturn(f func(context.Context, int64, string, []domain.Policy) error) *MockIRoleServiceUpdatePoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
