// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package testioc

import (
	"github.com/Duke1616/eiam/internal/pkg/searcher"
	"github.com/Duke1616/eiam/internal/repository"
	"github.com/Duke1616/eiam/internal/repository/dao"
	"github.com/Duke1616/eiam/internal/service/permission"
	"github.com/Duke1616/eiam/internal/service/policy"
	"github.com/Duke1616/eiam/internal/service/resource"
	"github.com/Duke1616/eiam/internal/service/role"
	"github.com/Duke1616/eiam/internal/service/tenant"
	"github.com/Duke1616/eiam/ioc"
)

// Injectors from wire.go:

func InitPermissionSuiteDeps() (*PermissionSuiteDeps, error) {
	db := InitDB()
	syncedEnforcer := ioc.InitCasbin(db)
	iTenantDAO := dao.NewTenantDAO(db)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	iUserDAO := dao.NewUserDAO(db)
	iUserRepository := repository.NewUserRepository(iUserDAO, iTenantDAO)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iPolicyDAO := dao.NewPolicyDAO(db)
	iPolicyRepository := repository.NewPolicyRepository(iPolicyDAO)
	iPolicyService := policy.NewPolicyService(iPolicyRepository)
	iRoleService := role.NewRoleService(iRoleRepository, iPolicyService)
	iTenantService := tenant.NewTenantService(iTenantRepository, iUserRepository, iRoleService, syncedEnforcer)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO)
	iServiceDAO := dao.NewServiceDAO(db)
	iServiceRepository := repository.NewServiceRepository(iServiceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository, iServiceRepository)
	iSubjectRegistry := ProvideTestSubjectRegistry()
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO)
	iAuthorizer := ioc.InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iPolicyService, iRoleService, iSubjectRegistry, iResourceService, iPermissionRepository, iAuthorizer)
	permissionSuiteDeps := &PermissionSuiteDeps{
		DB:          db,
		Enforcer:    syncedEnforcer,
		TenantSvc:   iTenantService,
		RoleSvc:     iRoleService,
		PolicySvc:   iPolicyService,
		ResourceSvc: iResourceService,
		PermSvc:     iPermissionService,
	}
	return permissionSuiteDeps, nil
}

// wire.go:

// ProvideTestSubjectRegistry 提供测试环境下空的主体注册中心
func ProvideTestSubjectRegistry() searcher.ISubjectRegistry {
	return searcher.NewSubjectRegistry()
}
