// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package testioc

import (
	"github.com/Duke1616/eiam/internal/repository"
	"github.com/Duke1616/eiam/internal/repository/dao"
	"github.com/Duke1616/eiam/internal/service/permission"
	"github.com/Duke1616/eiam/internal/service/policy"
	"github.com/Duke1616/eiam/internal/service/resource"
	"github.com/Duke1616/eiam/internal/service/role"
	"github.com/Duke1616/eiam/internal/service/tenant"
	"github.com/Duke1616/eiam/ioc"
)

// Injectors from wire.go:

func InitPermissionSuiteDeps() (*PermissionSuiteDeps, error) {
	db := InitDB()
	syncedEnforcer := ioc.InitCasbin(db)
	iTenantDAO := dao.NewTenantDAO(db)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iPolicyDAO := dao.NewPolicyDAO(db)
	iPolicyRepository := repository.NewPolicyRepository(iPolicyDAO)
	iPolicyService := policy.NewPolicyService(iPolicyRepository)
	iRoleService := role.NewRoleService(iRoleRepository, iPolicyService)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository)
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO)
	iAuthorizer := ioc.InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iRoleService, iResourceService, iPermissionRepository, iAuthorizer)
	iTenantService := tenant.NewTenantService(iTenantRepository, iPermissionService, iRoleService)
	permissionSuiteDeps := &PermissionSuiteDeps{
		DB:          db,
		Enforcer:    syncedEnforcer,
		TenantSvc:   iTenantService,
		RoleSvc:     iRoleService,
		ResourceSvc: iResourceService,
		PermSvc:     iPermissionService,
	}
	return permissionSuiteDeps, nil
}
