// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=idpmocks -destination=./mocks/service.mock.go -typed IService
//

// Package idpmocks is a generated GoMock package.
package idpmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	idp "github.com/Duke1616/eiam/internal/service/idp"
	jose "github.com/go-jose/go-jose/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockIService) Authorize(ctx context.Context, req idp.AuthorizeRequest) (*idp.AuthorizeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, req)
	ret0, _ := ret[0].(*idp.AuthorizeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockIServiceMockRecorder) Authorize(ctx, req any) *MockIServiceAuthorizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockIService)(nil).Authorize), ctx, req)
	return &MockIServiceAuthorizeCall{Call: call}
}

// MockIServiceAuthorizeCall wrap *gomock.Call
type MockIServiceAuthorizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceAuthorizeCall) Return(arg0 *idp.AuthorizeResult, arg1 error) *MockIServiceAuthorizeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceAuthorizeCall) Do(f func(context.Context, idp.AuthorizeRequest) (*idp.AuthorizeResult, error)) *MockIServiceAuthorizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceAuthorizeCall) DoAndReturn(f func(context.Context, idp.AuthorizeRequest) (*idp.AuthorizeResult, error)) *MockIServiceAuthorizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfirmConsent mocks base method.
func (m *MockIService) ConfirmConsent(ctx context.Context, consentID string, approved bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmConsent", ctx, consentID, approved)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmConsent indicates an expected call of ConfirmConsent.
func (mr *MockIServiceMockRecorder) ConfirmConsent(ctx, consentID, approved any) *MockIServiceConfirmConsentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmConsent", reflect.TypeOf((*MockIService)(nil).ConfirmConsent), ctx, consentID, approved)
	return &MockIServiceConfirmConsentCall{Call: call}
}

// MockIServiceConfirmConsentCall wrap *gomock.Call
type MockIServiceConfirmConsentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceConfirmConsentCall) Return(arg0 string, arg1 error) *MockIServiceConfirmConsentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceConfirmConsentCall) Do(f func(context.Context, string, bool) (string, error)) *MockIServiceConfirmConsentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceConfirmConsentCall) DoAndReturn(f func(context.Context, string, bool) (string, error)) *MockIServiceConfirmConsentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExchangeToken mocks base method.
func (m *MockIService) ExchangeToken(ctx context.Context, req domain.TokenRequest, issuerURL string) (*domain.OidcTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, req, issuerURL)
	ret0, _ := ret[0].(*domain.OidcTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockIServiceMockRecorder) ExchangeToken(ctx, req, issuerURL any) *MockIServiceExchangeTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockIService)(nil).ExchangeToken), ctx, req, issuerURL)
	return &MockIServiceExchangeTokenCall{Call: call}
}

// MockIServiceExchangeTokenCall wrap *gomock.Call
type MockIServiceExchangeTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceExchangeTokenCall) Return(arg0 *domain.OidcTokenResult, arg1 error) *MockIServiceExchangeTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceExchangeTokenCall) Do(f func(context.Context, domain.TokenRequest, string) (*domain.OidcTokenResult, error)) *MockIServiceExchangeTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceExchangeTokenCall) DoAndReturn(f func(context.Context, domain.TokenRequest, string) (*domain.OidcTokenResult, error)) *MockIServiceExchangeTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConsentInfo mocks base method.
func (m *MockIService) GetConsentInfo(ctx context.Context, consentID string) (*domain.ConsentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentInfo", ctx, consentID)
	ret0, _ := ret[0].(*domain.ConsentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsentInfo indicates an expected call of GetConsentInfo.
func (mr *MockIServiceMockRecorder) GetConsentInfo(ctx, consentID any) *MockIServiceGetConsentInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentInfo", reflect.TypeOf((*MockIService)(nil).GetConsentInfo), ctx, consentID)
	return &MockIServiceGetConsentInfoCall{Call: call}
}

// MockIServiceGetConsentInfoCall wrap *gomock.Call
type MockIServiceGetConsentInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceGetConsentInfoCall) Return(arg0 *domain.ConsentInfo, arg1 error) *MockIServiceGetConsentInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceGetConsentInfoCall) Do(f func(context.Context, string) (*domain.ConsentInfo, error)) *MockIServiceGetConsentInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceGetConsentInfoCall) DoAndReturn(f func(context.Context, string) (*domain.ConsentInfo, error)) *MockIServiceGetConsentInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDiscoveryConfig mocks base method.
func (m *MockIService) GetDiscoveryConfig(ctx context.Context, issuerURL string) domain.OidcDiscovery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscoveryConfig", ctx, issuerURL)
	ret0, _ := ret[0].(domain.OidcDiscovery)
	return ret0
}

// GetDiscoveryConfig indicates an expected call of GetDiscoveryConfig.
func (mr *MockIServiceMockRecorder) GetDiscoveryConfig(ctx, issuerURL any) *MockIServiceGetDiscoveryConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscoveryConfig", reflect.TypeOf((*MockIService)(nil).GetDiscoveryConfig), ctx, issuerURL)
	return &MockIServiceGetDiscoveryConfigCall{Call: call}
}

// MockIServiceGetDiscoveryConfigCall wrap *gomock.Call
type MockIServiceGetDiscoveryConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceGetDiscoveryConfigCall) Return(arg0 domain.OidcDiscovery) *MockIServiceGetDiscoveryConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceGetDiscoveryConfigCall) Do(f func(context.Context, string) domain.OidcDiscovery) *MockIServiceGetDiscoveryConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceGetDiscoveryConfigCall) DoAndReturn(f func(context.Context, string) domain.OidcDiscovery) *MockIServiceGetDiscoveryConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetJWKS mocks base method.
func (m *MockIService) GetJWKS(ctx context.Context) jose.JSONWebKeySet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWKS", ctx)
	ret0, _ := ret[0].(jose.JSONWebKeySet)
	return ret0
}

// GetJWKS indicates an expected call of GetJWKS.
func (mr *MockIServiceMockRecorder) GetJWKS(ctx any) *MockIServiceGetJWKSCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWKS", reflect.TypeOf((*MockIService)(nil).GetJWKS), ctx)
	return &MockIServiceGetJWKSCall{Call: call}
}

// MockIServiceGetJWKSCall wrap *gomock.Call
type MockIServiceGetJWKSCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceGetJWKSCall) Return(arg0 jose.JSONWebKeySet) *MockIServiceGetJWKSCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceGetJWKSCall) Do(f func(context.Context) jose.JSONWebKeySet) *MockIServiceGetJWKSCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceGetJWKSCall) DoAndReturn(f func(context.Context) jose.JSONWebKeySet) *MockIServiceGetJWKSCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserInfo mocks base method.
func (m *MockIService) GetUserInfo(ctx context.Context, tokenString string) (*domain.OidcUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, tokenString)
	ret0, _ := ret[0].(*domain.OidcUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockIServiceMockRecorder) GetUserInfo(ctx, tokenString any) *MockIServiceGetUserInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockIService)(nil).GetUserInfo), ctx, tokenString)
	return &MockIServiceGetUserInfoCall{Call: call}
}

// MockIServiceGetUserInfoCall wrap *gomock.Call
type MockIServiceGetUserInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceGetUserInfoCall) Return(arg0 *domain.OidcUserInfo, arg1 error) *MockIServiceGetUserInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceGetUserInfoCall) Do(f func(context.Context, string) (*domain.OidcUserInfo, error)) *MockIServiceGetUserInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceGetUserInfoCall) DoAndReturn(f func(context.Context, string) (*domain.OidcUserInfo, error)) *MockIServiceGetUserInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeToken mocks base method.
func (m *MockIService) RevokeToken(ctx context.Context, token, tokenTypeHint, clientID, clientSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token, tokenTypeHint, clientID, clientSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockIServiceMockRecorder) RevokeToken(ctx, token, tokenTypeHint, clientID, clientSecret any) *MockIServiceRevokeTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockIService)(nil).RevokeToken), ctx, token, tokenTypeHint, clientID, clientSecret)
	return &MockIServiceRevokeTokenCall{Call: call}
}

// MockIServiceRevokeTokenCall wrap *gomock.Call
type MockIServiceRevokeTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceRevokeTokenCall) Return(arg0 error) *MockIServiceRevokeTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceRevokeTokenCall) Do(f func(context.Context, string, string, string, string) error) *MockIServiceRevokeTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceRevokeTokenCall) DoAndReturn(f func(context.Context, string, string, string, string) error) *MockIServiceRevokeTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
