// Code generated by MockGen. DO NOT EDIT.
// Source: ./resource.go
//
// Generated by this command:
//
//	mockgen -source=./resource.go -package=resourcemocks -destination=./mocks/resource.mock.go -typed IResourceService
//

// Package resourcemocks is a generated GoMock package.
package resourcemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIResourceService is a mock of IResourceService interface.
type MockIResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockIResourceServiceMockRecorder
	isgomock struct{}
}

// MockIResourceServiceMockRecorder is the mock recorder for MockIResourceService.
type MockIResourceServiceMockRecorder struct {
	mock *MockIResourceService
}

// NewMockIResourceService creates a new mock instance.
func NewMockIResourceService(ctrl *gomock.Controller) *MockIResourceService {
	mock := &MockIResourceService{ctrl: ctrl}
	mock.recorder = &MockIResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResourceService) EXPECT() *MockIResourceServiceMockRecorder {
	return m.recorder
}

// CreateAPI mocks base method.
func (m *MockIResourceService) CreateAPI(ctx context.Context, a domain.API) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPI", ctx, a)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPI indicates an expected call of CreateAPI.
func (mr *MockIResourceServiceMockRecorder) CreateAPI(ctx, a any) *MockIResourceServiceCreateAPICall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPI", reflect.TypeOf((*MockIResourceService)(nil).CreateAPI), ctx, a)
	return &MockIResourceServiceCreateAPICall{Call: call}
}

// MockIResourceServiceCreateAPICall wrap *gomock.Call
type MockIResourceServiceCreateAPICall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIResourceServiceCreateAPICall) Return(arg0 int64, arg1 error) *MockIResourceServiceCreateAPICall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIResourceServiceCreateAPICall) Do(f func(context.Context, domain.API) (int64, error)) *MockIResourceServiceCreateAPICall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIResourceServiceCreateAPICall) DoAndReturn(f func(context.Context, domain.API) (int64, error)) *MockIResourceServiceCreateAPICall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateMenu mocks base method.
func (m_2 *MockIResourceService) CreateMenu(ctx context.Context, m domain.Menu) (int64, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateMenu", ctx, m)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMenu indicates an expected call of CreateMenu.
func (mr *MockIResourceServiceMockRecorder) CreateMenu(ctx, m any) *MockIResourceServiceCreateMenuCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenu", reflect.TypeOf((*MockIResourceService)(nil).CreateMenu), ctx, m)
	return &MockIResourceServiceCreateMenuCall{Call: call}
}

// MockIResourceServiceCreateMenuCall wrap *gomock.Call
type MockIResourceServiceCreateMenuCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIResourceServiceCreateMenuCall) Return(arg0 int64, arg1 error) *MockIResourceServiceCreateMenuCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIResourceServiceCreateMenuCall) Do(f func(context.Context, domain.Menu) (int64, error)) *MockIResourceServiceCreateMenuCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIResourceServiceCreateMenuCall) DoAndReturn(f func(context.Context, domain.Menu) (int64, error)) *MockIResourceServiceCreateMenuCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAPIByPath mocks base method.
func (m *MockIResourceService) FindAPIByPath(ctx context.Context, service, method, path string) (domain.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAPIByPath", ctx, service, method, path)
	ret0, _ := ret[0].(domain.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAPIByPath indicates an expected call of FindAPIByPath.
func (mr *MockIResourceServiceMockRecorder) FindAPIByPath(ctx, service, method, path any) *MockIResourceServiceFindAPIByPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAPIByPath", reflect.TypeOf((*MockIResourceService)(nil).FindAPIByPath), ctx, service, method, path)
	return &MockIResourceServiceFindAPIByPathCall{Call: call}
}

// MockIResourceServiceFindAPIByPathCall wrap *gomock.Call
type MockIResourceServiceFindAPIByPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIResourceServiceFindAPIByPathCall) Return(arg0 domain.API, arg1 error) *MockIResourceServiceFindAPIByPathCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIResourceServiceFindAPIByPathCall) Do(f func(context.Context, string, string, string) (domain.API, error)) *MockIResourceServiceFindAPIByPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIResourceServiceFindAPIByPathCall) DoAndReturn(f func(context.Context, string, string, string) (domain.API, error)) *MockIResourceServiceFindAPIByPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMenus mocks base method.
func (m *MockIResourceService) ListMenus(ctx context.Context, tenantId int64) ([]domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenus", ctx, tenantId)
	ret0, _ := ret[0].([]domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenus indicates an expected call of ListMenus.
func (mr *MockIResourceServiceMockRecorder) ListMenus(ctx, tenantId any) *MockIResourceServiceListMenusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenus", reflect.TypeOf((*MockIResourceService)(nil).ListMenus), ctx, tenantId)
	return &MockIResourceServiceListMenusCall{Call: call}
}

// MockIResourceServiceListMenusCall wrap *gomock.Call
type MockIResourceServiceListMenusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIResourceServiceListMenusCall) Return(arg0 []domain.Menu, arg1 error) *MockIResourceServiceListMenusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIResourceServiceListMenusCall) Do(f func(context.Context, int64) ([]domain.Menu, error)) *MockIResourceServiceListMenusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIResourceServiceListMenusCall) DoAndReturn(f func(context.Context, int64) ([]domain.Menu, error)) *MockIResourceServiceListMenusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
