// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository/cache (interfaces: IPermissionCache)
//
// Generated by this command:
//
//	mockgen -package=cachemocks -destination=./internal/repository/cache/mocks/permission.mock.go github.com/Duke1616/eiam/internal/repository/cache IPermissionCache
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPermissionCache is a mock of IPermissionCache interface.
type MockIPermissionCache struct {
	ctrl     *gomock.Controller
	recorder *MockIPermissionCacheMockRecorder
	isgomock struct{}
}

// MockIPermissionCacheMockRecorder is the mock recorder for MockIPermissionCache.
type MockIPermissionCacheMockRecorder struct {
	mock *MockIPermissionCache
}

// NewMockIPermissionCache creates a new mock instance.
func NewMockIPermissionCache(ctrl *gomock.Controller) *MockIPermissionCache {
	mock := &MockIPermissionCache{ctrl: ctrl}
	mock.recorder = &MockIPermissionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPermissionCache) EXPECT() *MockIPermissionCacheMockRecorder {
	return m.recorder
}

// ClearParentCodes mocks base method.
func (m *MockIPermissionCache) ClearParentCodes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearParentCodes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearParentCodes indicates an expected call of ClearParentCodes.
func (mr *MockIPermissionCacheMockRecorder) ClearParentCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearParentCodes", reflect.TypeOf((*MockIPermissionCache)(nil).ClearParentCodes), ctx)
}

// DeleteCodesByResources mocks base method.
func (m *MockIPermissionCache) DeleteCodesByResources(ctx context.Context, resURNs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCodesByResources", ctx, resURNs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCodesByResources indicates an expected call of DeleteCodesByResources.
func (mr *MockIPermissionCacheMockRecorder) DeleteCodesByResources(ctx, resURNs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCodesByResources", reflect.TypeOf((*MockIPermissionCache)(nil).DeleteCodesByResources), ctx, resURNs)
}

// GetCodesByResource mocks base method.
func (m *MockIPermissionCache) GetCodesByResource(ctx context.Context, resURN string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodesByResource", ctx, resURN)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCodesByResource indicates an expected call of GetCodesByResource.
func (mr *MockIPermissionCacheMockRecorder) GetCodesByResource(ctx, resURN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodesByResource", reflect.TypeOf((*MockIPermissionCache)(nil).GetCodesByResource), ctx, resURN)
}

// GetParentsByNeeds mocks base method.
func (m *MockIPermissionCache) GetParentsByNeeds(ctx context.Context, codes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentsByNeeds", ctx, codes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentsByNeeds indicates an expected call of GetParentsByNeeds.
func (mr *MockIPermissionCacheMockRecorder) GetParentsByNeeds(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentsByNeeds", reflect.TypeOf((*MockIPermissionCache)(nil).GetParentsByNeeds), ctx, codes)
}

// SetCodesByResource mocks base method.
func (m *MockIPermissionCache) SetCodesByResource(ctx context.Context, resURN string, codes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCodesByResource", ctx, resURN, codes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCodesByResource indicates an expected call of SetCodesByResource.
func (mr *MockIPermissionCacheMockRecorder) SetCodesByResource(ctx, resURN, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCodesByResource", reflect.TypeOf((*MockIPermissionCache)(nil).SetCodesByResource), ctx, resURN, codes)
}

// SetParentsByNeeds mocks base method.
func (m *MockIPermissionCache) SetParentsByNeeds(ctx context.Context, codes, parents []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetParentsByNeeds", ctx, codes, parents)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetParentsByNeeds indicates an expected call of SetParentsByNeeds.
func (mr *MockIPermissionCacheMockRecorder) SetParentsByNeeds(ctx, codes, parents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParentsByNeeds", reflect.TypeOf((*MockIPermissionCache)(nil).SetParentsByNeeds), ctx, codes, parents)
}
